import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hello, World!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon/16x16.svg" sizes="16x16" type="image/svg+xml" />
        <link rel="icon" href="/favicon/32x32.svg" sizes="32x32" type="image/svg+xml" />
        <link rel="icon" href="/favicon/48x48.svg" sizes="48x48" type="image/svg+xml" />
        <link rel="icon" href="/favicon/64x64.svg" sizes="64x64" type="image/svg+xml" />
        <link rel="icon" href="/favicon/128x128.svg" sizes="128x128" type="image/svg+xml" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="main-container">
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}